services:
  fizz-server:
    image: nginx
    container_name: 'fizz-container'
    volumes:
      - ./fizz-server:/usr/share/nginx/html
    ports:
      - 7000:80

  hoge-server:
    image: nginx
    container_name: 'hoge-container'
    volumes:
      - ./hoge-server:/usr/share/nginx/html
    ports:
      - 7001:80

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
